name: Build wtgutil

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "Build-Artifacts"

env:
  IS_PRERELEASE: ${{ inputs.is-prerelease }}
  UPLOAD_ARTIFACT: ${{ inputs.upload-artifact }}
  UPLOAD_TAG: ${{ inputs.upload-tag }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build (Release, x64)
        run: dotnet build ./src/wtgutil.csproj /p:Configuration=Release /p:Platform=x64

      - name: Upload artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: wtgutil-x64-Release
          path: ./src/bin/x64/Release/

      - name: Publish to GitHub Releases
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ env.IS_PRERELEASE }}
          files: ./src/bin/x64/Release/wtgutil.exe
          tag_name: ${{ env.UPLOAD_TAG }}