name: Build wtgutil (tag push)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-dotnet-build:
    uses: ./.github/workflows/dotnet-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
      version: ${{ github.ref_name }}
      is-prerelease: false

