name: Build wtgutil (CI)

on:
  push:
    branches:
      - master

jobs:
  run-dotnet-build:
    uses: ./.github/workflows/dotnet-build.yml
    secrets: inherit
    with:
      upload-artifact: false