name: Build wtgutil

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "Build-Artifacts"
      version:
        type: string
        default: "latest"

env:
  IS_PRERELEASE: ${{ inputs.is-prerelease }}
  UPLOAD_ARTIFACT: ${{ inputs.upload-artifact }}
  UPLOAD_TAG: ${{ inputs.upload-tag }}
  VERSION: ${{ inputs.version }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build x64 and AnyCPU Releases
        run: |
          dotnet build ./src/wtgutil.csproj /p:Configuration=Release /p:Platform=x64 -o ./src/bin/ActionsBuild/x64
          move ./src/bin/ActionsBuild/x64/wtgutil.exe ./src/bin/ActionsBuild/wtgutil-${{ env.VERSION }}-x64.exe
          dotnet build ./src/wtgutil.csproj /p:Configuration=Release /p:Platform=AnyCPU -o ./src/bin/ActionsBuild/AnyCPU
          move ./src/bin/ActionsBuild/AnyCPU/wtgutil.exe ./src/bin/ActionsBuild/wtgutil-${{ env.VERSION }}-x86_64.exe


      - name: Upload artifacts
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: wtgutil-Release
          path: ./src/bin/ActionsBuild/wtgutil-*.exe

      - name: Publish to GitHub Releases
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ env.IS_PRERELEASE }}
          files: ./src/bin/ActionsBuild/wtgutil-*.exe
          tag_name: ${{ env.UPLOAD_TAG }}